services:
  elasticsearch:
    container_name: els
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.1'
          memory: '256M'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.1'
          memory: '256M'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - elastic

  api:
    container_name: application_1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5121:8080"  # Externo:Interno
    networks:
      - elastic
    environment:
        ASPNETCORE_ENVIRONMENT: Production
        ElasticConfiguration__Uri: http://els:9200

   
  api_2:
    container_name: application_2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5131:8080"  # Externo:Interno
    networks:
      - elastic
    environment:
        ASPNETCORE_ENVIRONMENT: Production
        ElasticConfiguration__Uri: http://els:9200
 

  api_3:
    container_name: application_3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5141:8080"  # Externo:Interno
    networks:
      - elastic
    environment:
        ASPNETCORE_ENVIRONMENT: Production
        ElasticConfiguration__Uri: http://els:9200

networks:
  elastic:
    driver: bridge

volumes:
  grafana-storage:    
  elasticsearch-data: 